# Generated by Django 5.2.2 on 2025-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cor',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalatividade',
            name='cor',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
    ]
